# https://yarnpkg.com/configuration/yarnrc

changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - '!{lib/**,{CHANGELOG,LICENSE,README}.md,package.json}'

compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableInlineBuilds: true

enableTransparentWorkspaces: false

injectEnvironmentFiles:
  - .env.repo?

nmHoistingLimits: dependencies

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs
